version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
       - postgres:/data/postgres
       - ./init/:/docker-entrypoint-initdb.d/


  cloudbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver
    ports:
      - '8978:8978'
    volumes: 
      - cloudbeaver:/opt/cloudbeaver/workspace            

volumes:
    postgres:
    cloudbeaver: